# ------- results table

sql_result_create_table: 'CREATE TABLE IF NOT EXISTS results (
    id TEXT PRIMARY KEY,
    aggregation TEXT,
    Weighting TEXT,
    Num_crits INTEGER,
    Num_epics INTEGER,
    DPC TEXT,
    Backlog TEXT,
    tot_error INTEGER,
    WMAE REAL,
    N_WMAE REAL
)'

sql_result_insert_into: 'INSERT INTO results (id, aggregation, Weighting, Num_crits, Num_epics, DPC, Backlog, tot_error, WMAE, N_WMAE)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'

# ------- cod_estimation table

sql_cod_estimation_create_table: 'CREATE TABLE IF NOT EXISTS cod_estimation (
    session_id TEXT PRIMARY KEY,
    results_id TEXT,
    epic_name TEXT,
    epic_id TEXT,
    true_cod INTEGER,
    pred_cod INTEGER,
    class_difference INTEGER,
    error INTEGER,
    FOREIGN KEY (session_id) REFERENCES results(id)
)'

sql_cod_estimation_insert_into: 'INSERT INTO cod_estimation (session_id, results_id, epic_name, epic_id, true_cod, pred_cod, class_difference, error)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)'


# --------- aggregation table

sql_aggregation_create_table: 'CREATE TABLE IF NOT EXISTS aggregation (
    session_id TEXT,
    project_id TEXT PRIMARY KEY,
    epic_name TEXT,
    epic_id TEXT,
    aggregated_value REAL,
    aggregation_strategy TEXT,
    backlog TEXT,
    true_cod INTEGER,
    FOREIGN KEY (project_id) REFERENCES cod_estimation(results_id)
)'


sql_aggregation_insert_into: 'INSERT INTO aggregation (session_id, project_id, epic_name, epic_id, aggregated_value, aggregation_strategy, backlog, true_cod)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)'




# ------- wowa table

sql_wowa_create_table: 'CREATE TABLE IF NOT EXISTS wowa (
    project_id TEXT PRIMARY KEY,
    aggregated_value REAL,
    position INTEGER,
    criteria TEXT,
    criteria_value REAL,
    p_weight_current REAL,
    p_weight_previous REAL,
    omega_star_current REAL,
    omega_star_previous REAL,
    wowa_weight REAL,
    weighted_criteria_val REAL,
    FOREIGN KEY (project_id) REFERENCES aggregation(project_id)
)'

sql_wowa_insert_into: 'INSERT INTO wowa (project_id, aggregated_value, position, criteria, criteria_value, p_weight_current, p_weight_previous, omega_star_current, omega_star_previous, wowa_weight, weighted_criteria_val)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'