# Mapping dictionaries
mapping_class_to_Fib:
  1: 1
  2: 2
  3: 3
  4: 5
  5: 8
  6: 13
  7: 20
  8: 40
  9: 100



# Mapping dictionaries
mapping_Fib_to_class:
    1: 1
    2: 2
    3: 3
    5: 4
    8: 5
    13: 6
    21: 7
    40: 8
    100: 9